theme: jekyll-theme-cayman
tittle: Welcome to the adventures of my writting's homepage
description: If you want to see any of my writtings or everytime i finish a chapter your gonna have to bookmark this page.
